[upstream]
endpoint  = "https://preview.utxorpc-v0.demeter.run"
intersect = "tip"
# api_key set via DMTR_API_KEY env

[upstream.filter]
mints_policy_id = "4672f28ce36e492e722392359f71e9a9442646f81d856f92d7e163f1"

[storage]
database_path = "./tracker.db"

[[sources]]
name      = "ticketing-2026-preview"
tii_path  = "./protocols/buidler-fest/ticketing-2026.tii"
profile   = "preview"
